config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/permission.rb
class Permission < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :permissions

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user_list = User.all
    @users_permissions_list = @user_list.map do |user|
      [user, Permission.find(user.permissions_id || 1)]
    end
    @user = User.new
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @permissions = Permission.find(@user.permissions_id)
  end

  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to users_path
    flash[:notice] = 'User was deleted.'
  end

  def create
    permissions_id = map_permissions
    @user = User.new(user_params)
    @user.permissions_id = permissions_id
    @user.save!
    redirect_to users_path
    flash[:notice] = 'New user was created!'
  # TODO: get the form validation working
  # rescue ValidationError
  #   flash.now[:alert] = 'Error. Please fix your form.'
  #   render :index
  #   # raise
  end

  def update
    permissions_id = map_permissions
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)
    @user.permissions_id = permissions_id
    @user.save!
    redirect_to users_path
    flash[:notice] = 'User was updated!'
  end

  private

  def user_params
    params.require(:user).permit(
      %i[name email password]
    )
  end

  def map_permissions
    read = params[:read] == 'on' ? true : false
    write = params[:write] == 'on' ? true : false
    trash = params[:trash] == 'on' ? true : false

    permissions_id = 0
    permissions_map = [
      [true, true, true],
      [true, true, false],
      [true, false, false],
      [false, false, false],
      [false, false, true],
      [false, true, true],
      [false, true, false],
      [true, false, true]
    ]

    params_arr = [read, write, trash]

    permissions_map.each_with_index  do |permission, index|
      permissions_id = index if permission == params_arr
    end

    permissions_id + 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Userapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_confirm_delete_modal.html.erb
<div tabindex="-1" role="dialog" class="modal fade in confirm-delete-modal" data-delete-modal="" data-delete-action="<%= user_path(id: '') %>">
  <div role="document" class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title">Delete User</h2>
          <button type="button" data-dismiss="modal" aria-label="Close" class="close">
            <i class="ss-icon ss-delete"></i>
          </button>
        </div>
        <div class="modal-body">
          <h3>Are you sure?</h3>
          <p>You will not get this user back. Gone forever.</p>
        </div>
        <div class="modal-footer">
          <%= form_for('', url: user_path(id: ''), method: 'delete') do |f| %>
              <button type="button" class="btn btn-outlined" data-dismiss="modal">
                Cancel
              </button>
              <button type="submit" class="btn btn-default">
                Delete User
              </button>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <header class="page-header">
    <h1>User Manager</h1>
  </header>
<% if @user %>
  <section id="user-new" class="panel panel-primary">
    <div class="panel-heading"><h2>Edit User</h2></div>
    <div class="panel-body">
      <div>
        <%= form_for(:user, url: { action: "update" }, format: :json, method: :put) do |f| %>
           <div class="row form-group">
            <div class="col-xs-2"><label for="name">Name</label></div>
            <div class="col-xs-10"><%= f.text_field :name %></div>
          </div>
          <div class="row form-group">
            <div class="col-xs-2"><label for="email">Email</label></div>
            <div class="col-xs-10"><%= f.text_field :email %></div>
          </div>
          <div class="row form-group">
            <div class="col-xs-2"><label for="email">Password</label></div>
            <div class="col-xs-10"><%= f.text_field :password %></div>
          </div>
          <div class="row form-group">
            <div class="col-xs-2"><label>Permissions</label></div>
            <div class="col-xs-10">
              <input type="checkbox" name="read" <%= 'checked' if @permissions.read %>/>
              <label for="read">Read</label>
              <input type="checkbox" name="write" <%= 'checked' if @permissions.write %> />
              <label for="write">Write</label>
              <input type="checkbox" name="trash" <%= 'checked' if @permissions.trash %> />
              <label for="trash">Delete</label>
            </div>
          </div>
          <div class="row">
             <div class="col-xs-12">
               <button type="submit" class="btn btn-primary">Update User</button>
            </div>
          </div>
        <% end %>
        </div>
      </div>
    </section>
  <% else %>
    No such user exists.
  <% end %>
</div>

app/views/users/index.html.erb
<% if @users_permissions_list %>
<div class="container">
  <header class="page-header">
    <h1>User Manager</h1>
  </header>
  <% if !flash.empty? %>
    <div class="panel panel-warning">
        <% flash.keys.each do |k| %>
            <div class="panel-heading">
              <h4>Notice:</h4><%= flash[k] %>
            </div>
        <% end %>
    </div>
  <% end %>
  <section id="user-new" class="panel panel-primary">
    <div class="panel-heading"><h2>Create New User</h2></div>
    <div class="panel-body">
      <div class="container">
        <%= form_for(:user, url: { action: "create" }, format: :json, method: :post) do |f| %>
          <div class="row form-group">
            <div class="col-xs-2"><label for="name">Name</label></div>
            <div class="col-xs-10"><%= f.text_field :name %></div>
          </div>
          <div class="row form-group">
            <div class="col-xs-2"><label for="email">Email</label></div>
            <div class="col-xs-10"><%= f.text_field :email %></div>
          </div>
          <div class="row form-group">
            <div class="col-xs-2"><label for="email">Password</label></div>
            <div class="col-xs-10"><%= f.text_field :password %></div>
          </div>
          <div class="row form-group">
            <div class="col-xs-2"><label>Permissions</label></div>
            <div class="col-xs-10">
              <input type="checkbox" name="read" />
              <label for="read">Read</label>
              <input type="checkbox" name="write" />
              <label for="write">Write</label>
              <input type="checkbox" name="trash" />
              <label for="trash">Delete</label>
            </div>
          </div>
          <div class="row">
             <div class="col-xs-12">
               <button type="submit" class="btn btn-primary">Create New User</button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
  <section id="user-list"  class="panel panel-primary">
    <div class="panel-heading"><h2>User List</h2></div>
    <div class="panel-body">
      <table class="table table-responsive table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Read</th>
            <th>Write</th>
            <th>Delete</th>
            <th></th>
          </tr>
        </thead>
        <% @users_permissions_list.each do |user|  %>
        <tr>
          <td class="col-xs-2"><%= user[0].name %></td>
          <td class="col-xs-2"><%= user[0].email %></td>
          <td class="col-xs-1"><span class="glyphicon <% if user[1].read %>glyphicon-ok<% else %>glyphicon-remove<% end %>"></span></td>
          <td class="col-xs-1"><span class="glyphicon <% if user[1].write %>glyphicon-ok<% else %>glyphicon-remove<% end %>"></td>
          <td class="col-xs-1"><span class="glyphicon <% if user[1].trash %>glyphicon-ok<% else %>glyphicon-remove<% end %>"></td>
          <td class="col-xs-2">
            <div  style="display: flex;">
              <a href="<%= edit_user_path(user[0].id) %>" class="btn btn-default" style="margin-right: 10px;">Edit</a>
              <%= form_for('', url: user_path(user[0].id), method: 'delete') do |f| %>
                <button type="submit" class="btn btn-default">Delete</button>
              <% end %>
            </div>
              <!-- TODO: get confirm modal working<a title="delete" data-toggle="modal" data-target=".confirm-delete-modal"
              data-user-id="<%= user[0].id %>" data-delete>Delete</a>-->
          </td>
        </tr>
        <% end %>
      <% end %>
      </table>
    </div>
  </section>
  <%= render partial: 'confirm_delete_modal' %>
</div>